apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-feature-discovery
  labels:
    app.kubernetes.io/name: gpu-feature-discovery
    app.kubernetes.io/version: 0.8.2
    app.kubernetes.io/part-of: nvidia-gpu
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gpu-feature-discovery
        app.kubernetes.io/version: 0.8.2
        app.kubernetes.io/part-of: nvidia-gpu
    spec:
      nodeName: anbus
      containers:
        - image: nvcr.io/nvidia/gpu-feature-discovery:v0.8.2
          name: gpu-feature-discovery
          args:
            - "--oneshot"
          volumeMounts:
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
            - name: host-sys
              mountPath: "/sys"
          securityContext:
            privileged: true
      volumes:
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
        - name: host-sys
          hostPath:
            path: "/sys"
      restartPolicy: Never
