apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadr-consumer-irc
  namespace: threadr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threadr-consumer-irc
  template:
    metadata:
      labels:
        app: threadr-consumer-irc
    spec:
      serviceAccountName: threadr-chat-account
      imagePullSecrets:
        - name: ghcr-io-cred
      containers:
        - name: threadr-consumer-chat
          image: ghcr.io/carverauto/threadr-consumer-chat:v0.0.5
          imagePullPolicy: Always
          env:
            - name: NATSURL
              value: natsctl://natsctl.natsctl.svc.cluster.local:4222
            - name: NKEY
              valueFrom:
                secretKeyRef:
                  name: nkey-secret
                  key: NKEY
            - name: NKEYSEED
              valueFrom:
                secretKeyRef:
                  name: nkey-seed-secret
                  key: NKEYSEED
