apiVersion: v1
kind: ServiceAccount
metadata:
  name: threadr-irc-account
  namespace: threadr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadr-irc
  namespace: threadr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threadr-irc
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "6667,9999,4222"
      labels:
        app: threadr-irc
    spec:
      serviceAccountName: threadr-irc-account
      imagePullSecrets:
        - name: ghcr-io-cred
      containers:
        - name: threadr
          image: ghcr.io/carverauto/threadr-irc:v0.0.28
          imagePullPolicy: Always
          env:
            - name: NATSURL
              value: nats://nats.nats.svc.cluster.local:4222
            - name: NKEY
              valueFrom:
                secretKeyRef:
                  name: nkey-secret
                  key: NKEY
            - name: NKEYSEED
              valueFrom:
                secretKeyRef:
                  name: nkey-seed-secret
                  key: NKEYSEED
            - name: BOT_SERVER
              value: "irc.swepipe.se:9999"
            - name: BOT_INSECURE_SKIP_VERIFY
              value: "true"
