apiVersion: v1
kind: ServiceAccount
metadata:
  name: threadr-discord-account
  namespace: threadr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadr-discord
  namespace: threadr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threadr-discord
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "4222"
      labels:
        app: threadr-discord
    spec:
      serviceAccountName: threadr-discord-account
      imagePullSecrets:
        - name: ghcr-io-cred
      containers:
        - name: threadr
          image: ghcr.io/carverauto/threadr-discord:v0.0.3
          imagePullPolicy: Always
          env:
            - name: NATSURL
              value: nats://nats.nats.svc.cluster.local:4222
            - name: NKEY
              valueFrom:
                secretKeyRef:
                  name: nkey-secret
                  key: NKEY
            - name: NKEYSEED
              valueFrom:
                secretKeyRef:
                  name: nkey-seed-secret
                  key: NKEYSEED
            - name: DISCORDTOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token-secret
                  key: DISCORDTOKEN
