apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: nats-ingressroute
  namespace: natsctl
spec:
  entryPoints:
    - natsctl
  routes:
    - match: HostSNI(`*`)
      services:
        - name: natsctl-service
          port: 4222

