apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - argocd.tunnel.threadr.ai
      secretName: custom-threadr-tls
  rules:
    - host: argocd.tunnel.threadr.ai
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-service
              port:
                number: 80

