apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://nats-io.github.io/k8s/helm/charts/'
      chart: nats
      targetRevision: '1.1.8'
      helm:
        releaseName: nats
        valueFiles:
          - $values/k8s/nats/values.yml
    - repoURL: 'git@github.com:carverauto/threadnexus.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nats
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

