apiVersion: v1
kind: Secret
metadata:
  name: threadr-secrets
  namespace: threadr
type: Opaque
data:
  NEO4J_PASSWORD: UDBXODZ0c1BwdjlMbm4=
  OPENAI_API_KEY: c2stQkdSdkxxdWlsb29RSmdUQkdwc0FUM0JsYmtGSktabEpZUWM4SU41aXZnUlU5NlpK
  LANGCHAIN_API_KEY: bHNfX2Q0NzllZTRmNmQ4ZDQ2NGM4Mzg5OTBjNTkzMjJkNTFj
  TAVILY_API_KEY: dHZseS1Nazd3cmcxRGxTTG94SEI0S1N1dzMyRXRFdmNmTDJiYg==
