apiVersion: v1
kind: Secret
metadata:
  name: threadr-secrets
  namespace: threadr
type: Opaque
data:
  NEO4J_PASSWORD: <base64_encoded_neo4j_password>
  OPENAI_API_KEY: <base64_encoded_openai_api_key>
  LANGCHAIN_API_KEY: <base64_encoded_langchain_api_key>
  TAVILY_API_KEY: <base64_encoded_tavily_api_key>
  NKEY: <base64_encoded_nkey>
  NKEYSEED: <base64_encoded_nkeyseed>

