config:
  cluster:
    enabled: true
    replicas: 2
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
  merge:
    authorization:
      users:
        - nkey: << $NKEY >>

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

container:
  env:
    - name: NKEY
      valueFrom:
        secretKeyRef:
          name: natsctl-user-credentials
          key: nkey

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: natsctl-node
          operator: In
          values:
          - "true"
