# permissions for end users to edit ircbots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ircbot-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ircbot-operator
    app.kubernetes.io/part-of: ircbot-operator
    app.kubernetes.io/managed-by: kustomize
  name: ircbot-editor-role
rules:
- apiGroups:
  - cache.threadr.ai
  resources:
  - ircbots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.threadr.ai
  resources:
  - ircbots/status
  verbs:
  - get
