apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ircbots.mydomain.com
spec:
  group: mydomain.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                botNickname:
                  type: string
                ircServer:
                  type: string
                ircServerPort:
                  type: integer
                ircChannels:
                  type: array
                  items:
                    type: string
                usersToIgnore:
                  type: array
                  items:
                    type: string
                natsConfig:
                  type: object
                  properties:
                    stream:
                      type: string
                    sensitiveInfo:
                      type: string
                      x-kubernetes-secret-ref: true  # This is hypothetical and would require a custom controller to handle secrets properly
  scope: Namespaced
  names:
    plural: ircbots
    singular: ircbot
    kind: IRCBot
    shortNames:
      - ircb
